apiVersion: v1
kind: Pod
metadata:
  name: echo-pod
  labels: 
    app: echo-pod
spec:
  containers:
    - name: echo-pod-container
      image: anvesh35/echo-pod-name:latest
      env:
        - name: NODE_NAME
          value: MY_WORKER_NODE
          # valueFrom:
          #   fieldRef:
          #     fieldPath: spec.nodeName
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: echo-svc
spec:
  type: NodePort
  selector:
    app: echo-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80