apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod
  labels:
    env: prod
spec:
  containers:
  - name: nginxpod
    image: nginx
  tolerations:
  - key: "env"
    operator: "Equal"
    value: "prod"
    effect: "NoSchedule"