apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argocd-private-repo
  namespace: argocd
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/anveshmuppeda/argo-cd-demo.git
  username: argocd-classic2
  password: <my-token>