kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-user-access-rolebinding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-user-full-access-role
subjects:
- kind: User
  namespace: dev
  #name: groupObjectId
  name: anvesh
  apiGroup: rbac.authorization.k8s.io  