apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app2
  namespace: fluxcd-demo
spec:
  interval: 1m0s
  ref:
    branch: fluxcd
  url: https://github.com/anveshmuppeda/kubernetes
  secretRef:
    name: app2-githubsecret