apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app1
  namespace: fluxcd-demo
spec:
  interval: 15m
  path: "./projects/eks-flux/manifests/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: app1