apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-router-app
  labels:
    app: simple-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-router
  template:
    metadata:
      labels:
        app: simple-router
    spec:
      containers:
      - name: simple-router-container
        image: anvesh35/simple-router:v1.0.0
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 80
