---
apiVersion: v1
kind: Namespace
metadata:
  name: backup-tools
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-argocd-backup
rules:
  - apiGroups: [""]
    resources: ["pods","configmaps","secrets"]
    verbs: ["get","list","watch"]
  - apiGroups: ["argoproj.io"]
    resources: [ "*"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-role-argocd-backup
subjects:
  - kind: ServiceAccount
    name: sa-argocd-backup
    namespace: backup-tools
roleRef:
  kind: ClusterRole
  name: role-argocd-backup
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: argocd-backup
  namespace: backup-tools
spec:
  schedule: "42 16 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-argocd-backup
          containers:
          - image: quay.io/argoproj/argocd:v2.6.7
            imagePullPolicy: Always
            name: backup
            command: ["sh", "-c", "apt-get update && apt-get install awscli -y && argocd admin export -n argocd > backup-$(date +%Y-%m-%d_%H)_pod-$HOSTNAME.yml"]
            securityContext:
              runAsUser: 0
          restartPolicy: Never