apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  storageClassName: my-own-sc
  accessModes:
    - ReadWriteOnce # the volume can be mounted as read-write by a single node.
  resources:
    requests:
      storage: 1Gi