# .github/workflows/docker-build-push.yaml
name: EKS FluxCD Project | App - Docker Build

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Version bump type'
        required: true
        default: 'minor'
        type: choice
        options:
        - major
        - minor
        - patch
  push:
    branches:
      - main
      - feature/eksFluxCDProject
    paths:
      - 'projects/eks-flux/app'

jobs:
  build-push-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (with all branches)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: feature/eksFluxCDProject
      
      - name: Prepare version
        id: prep
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            BUILD_IMAGE=true
          else
            VERSION=${GITHUB_SHA::8}
            BUILD_IMAGE=true
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "IMAGE=anvesh35/eks-flux-project-app:$VERSION" >> $GITHUB_ENV
          echo "BUILD_IMAGE=$BUILD_IMAGE" >> $GITHUB_ENV


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (Simple App)
        uses: docker/build-push-action@v4
        with:
          context: projects/eks-flux/app/
          file: projects/eks-flux/app/Dockerfile
          push: true
          tags: |
            anvesh35/eks-flux-project-app:latest
            anvesh35/eks-flux-project-app:${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ env.VERSION }}
      
      - name: Update Kubernetes manifests
        run: |
          # sed -i "s|image: anvesh35/eks-flux-project-app:.*|image: ${{ env.IMAGE }}|" projects/eks-flux/manifests/app1-deployment.yaml
          sed -i "s|image:.*|image: anvesh35/eks-flux-project-app:${{ env.VERSION }}|" projects/eks-flux/manifests/app1-deployment.yaml
          git config user.name "FluxCDBot CI"
          git config user.email "fluxcdbot@users.noreply.github.com"

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          add: |
            - projects/eks-flux/manifests/app1-deployment.yaml
          message: "Update image to ${{ env.VERSION }}"
          signoff: true
          push: true
          branch: feature/eksFluxCDProject
          author_name: "Fluxcdbot CI"
          author_email: "fluxcdbot@users.noreply.github.com"
          #token: ${{ secrets.PR_PAT_TOKEN }}
      