# .github/workflows/docker-build-push.yaml
name: K8s-Tools | eksctl - Docker Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to use for the Docker image(vx.y.z)'
        required: true
        default: 'v0.150.0'
        type: choice
        options:
        - v0.150.0
        - v0.140.0
  push:
    branches:
      - main
      - dev
    paths:
      - 'dockerfiles/k8s-tools/eksctl/Dockerfile'

jobs:
  build-push-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (with all branches)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: dev

      - name: Prepare version
        id: prep
        run: |
          if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            VERSION=${{ github.event.inputs.version }}
          else
            VERSION=${GITHUB_SHA::8}
          fi
          BUILD_IMAGE=true
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "IMAGE=anvesh35/k8s-tools:eksctl-$VERSION" >> $GITHUB_ENV
          echo "EKSCTLIMAGE=anvesh35/eksctl-cli:$VERSION" >> $GITHUB_ENV
          echo "LATESTEKSCTLIMAGE=anvesh35/eksctl-cli:latest" >> $GITHUB_ENV
          echo "BUILD_IMAGE=$BUILD_IMAGE" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        if: env.BUILD_IMAGE == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: env.BUILD_IMAGE == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push k8s-tools Docker image
        if: env.BUILD_IMAGE == 'true'
        uses: docker/build-push-action@v4
        with:
          context: dockerfiles/k8s-tools/eksctl/
          file: dockerfiles/k8s-tools/eksctl/Dockerfile
          push: true
          tags: ${{ env.IMAGE }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ env.VERSION }}
      
      - name: Build and push eksctl Docker image
        if: env.BUILD_IMAGE == 'true'
        uses: docker/build-push-action@v4
        with:
          context: dockerfiles/k8s-tools/eksctl/
          file: dockerfiles/k8s-tools/eksctl/Dockerfile
          push: true
          tags: |
            ${{ env.EKSCTLIMAGE }}
            ${{ env.LATESTEKSCTLIMAGE }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ env.VERSION }}
