# .github/workflows/docker-build-push.yaml
name: K8s-Tools | All-In-One - Docker Build 

on:
  workflow_dispatch:
    inputs:
      kubectl-version:
        description: 'Version to use for the kubectl client'
        required: true
        default: '1.29.3'
        type: choice
        options:
        - 1.29.3
        - 1.28.3
      velero-version:
        description: 'Version to use for the Velero client'
        required: true
        default: '1.12.2'
        type: choice
        options:
        - 1.12.2
        - 1.12.1
      helm-version:
        description: 'Version to use for the Helm client'
        required: true
        default: '3.14.4'
        type: choice
        options:
        - 3.14.4
        - 3.14.3
      argocd-version:
        description: 'Version to use for the ArgoCD client'
        required: true
        default: '2.8.3'
        type: choice
        options:
        - 2.8.3
        - 2.8.2
      flux-version:
        description: 'Version to use for the FluxCD client'
        required: true
        default: '2.1.0'
        type: choice
        options:
        - 2.1.0
        - 2.0.0
      eksctl-version:
        description: 'Version to use for the EKSCTL client'
        required: true
        default: '0.150.0'
        type: choice
        options:
        - 0.150.0
        - 0.149.0

  push:
    branches:
      - main
      - dev
    paths:
      - 'dockerfiles/k8s-tools/allinone/Dockerfile'

jobs:
  build-push-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (with all branches)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: dev

      - name: Prepare version
        id: prep
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            BUILD_IMAGE=true
          else
            VERSION=${GITHUB_SHA::8}
            BUILD_IMAGE=true
          fi
          BUILD_IMAGE=true
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "ALLINONEIMAGE=anvesh35/k8s-tools:allinone-$VERSION" >> $GITHUB_ENV
          echo "LATESTALLINONEIMAGE=anvesh35/k8s-tools:latest" >> $GITHUB_ENV
          echo "BUILD_IMAGE=$BUILD_IMAGE" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        if: env.BUILD_IMAGE == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: env.BUILD_IMAGE == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push All-In-One Docker image
        if: env.BUILD_IMAGE == 'true'
        uses: docker/build-push-action@v4
        with:
          context: dockerfiles/k8s-tools/allinone/
          file: dockerfiles/k8s-tools/allinone/Dockerfile
          push: true
          tags: |
            ${{ env.ALLINONEIMAGE }}
            ${{ env.LATESTALLINONEIMAGE }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            KUBECTL_VERSION=${{ github.event.inputs.kubectl-version }}
            VELERO_VERSION=${{ github.event.inputs.velero-version }}
            HELM_VERSION=${{ github.event.inputs.helm-version }}
            ARGOCD_VERSION=${{ github.event.inputs.argocd-version }}
            FLUX_VERSION=${{ github.event.inputs.flux-version }}
            EKSCTL_VERSION=${{ github.event.inputs.eksctl-version }}
